using System;

namespace NAudio.Dmo
{
	[Flags]
	internal enum OutputStreamInfoFlags
	{
		DMO_OUTPUT_STREAMF_WHOLE_SAMPLES = 0x1,
		DMO_OUTPUT_STREAMF_SINGLE_SAMPLE_PER_BUFFER = 0x2,
		DMO_OUTPUT_STREAMF_FIXED_SAMPLE_SIZE = 0x4,
		DMO_OUTPUT_STREAMF_DISCARDABLE = 0x8,
		DMO_OUTPUT_STREAMF_OPTIONAL = 0x10
	}
}
