namespace ValveResourceFormat
{
	public enum ResourceType
	{
		Unknown,
		[Extension("vanim")]
		Animation,
		[Extension("vagrp")]
		AnimationGroup,
		[Extension("valst")]
		ActionList,
		[Extension("vseq")]
		Sequence,
		[Extension("vpcf")]
		Particle,
		[Extension("vmat")]
		Material,
		[Extension("vmks")]
		Sheet,
		[Extension("vmesh")]
		Mesh,
		[Extension("vtex")]
		Texture,
		[Extension("vmdl")]
		Model,
		[Extension("vphys")]
		PhysicsCollisionMesh,
		[Extension("vsnd")]
		Sound,
		[Extension("vmorf")]
		Morph,
		[Extension("vrman")]
		ResourceManifest,
		[Extension("vwrld")]
		World,
		[Extension("vwnod")]
		WorldNode,
		[Extension("vvis")]
		WorldVisibility,
		[Extension("vents")]
		EntityLump,
		[Extension("vsurf")]
		SurfaceProperties,
		[Extension("vsndevts")]
		SoundEventScript,
		[Extension("vsndstck")]
		SoundStackScript,
		[Extension("vfont")]
		BitmapFont,
		[Extension("vrmap")]
		ResourceRemapTable,
		[Extension("vtxt")]
		Panorama,
		[Extension("vcss")]
		PanoramaStyle,
		[Extension("vxml")]
		PanoramaLayout,
		[Extension("vpdi")]
		PanoramaDynamicImages,
		[Extension("vjs")]
		PanoramaScript,
		[Extension("vpsf")]
		ParticleSnapshot,
		[Extension("vmap")]
		Map
	}
}
